version: '3'
services:
  node:
    container_name: backend
    restart: always
    build: .
    ports:
      - '80:3000'
    volumes:
      - ./:/code
    external_links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27018:27017'
    volumes:
      - mongodb:/data/db
volumes:
  mongodb: